### ISSUE TITLE
Pin python version to 3.9 or update dependencies to work with 3.10+?

### ISSUE THREAD

**Issue by Tardo** [OCA/oca-addons-repo-template#127]
## Module
.pre-commit-config.yaml.jinja

## Describe the bug
`AttributeError: module 'collections' has no attribute 'MutableSet'`
I have the same issue reported here https://github.com/OCA/oca-addons-repo-template/issues/80 but in my local environment.

## To Reproduce
1. that python3 is pointing to python3.10 on your system 
2. run pre-commit in an OCA repo

**Expected behavior**
pre-commit ends successfully

**Additional context**
Exists a PR to add compatibility to 3.10: https://github.com/OCA/pylint-odoo/issues/360

**Possible temporal fix**
Pin the version to 3.9 instead of 3.x in the `default_language_version` variable

**Comment by pedrobaeza** [comment]
I think pinning the Python version is the better option for now

**Comment by Yajo** [comment]
> Pin the version to 3.9 instead of 3.x in the `default_language_version` variable

If I'm not wrong, pre-commit will not download a 3.9 binary for you. Instead it will fail if it doesn't find a python 3.9 one. That complicates a lot stuff for people on more modern distros.
